name: linting

on: [push, pull_request]

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
    - name: Get repository code
      uses: actions/checkout@v4
    - name: Get all changed .py files
      id: changed-py-files
      uses: tj-actions/changed-files@v42
      with:
        files: |
           **.py
    - name: List all changed files
      env:
        ALL_CHANGED_FILES: ${{ steps.changed-py-files.outputs.all_changed_files }}
      run: |
        for file in "$ALL_CHANGED_FILES"; do
          echo "$file was changed"
          done
    - name: Set up Python 3.9
      if: steps.changed-py-files.outputs.any_changed == 'true'
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    - name: Install dependencies
      if: steps.changed-py-files.outputs.any_changed == 'true'
      run: |
        python -m pip install --upgrade pip
        pip install -r model_inference/requirements.txt
    - name: Analysing the code with pylint
      if: steps.changed-py-files.outputs.any_changed == 'true'
      run: |
        pylint $(git ls-files '*.py')
    
